### ISSUE TITLE
Relative paths break in tag files

### ISSUE THREAD

**Issue by bcartmell** [tompascall/riot-jest-transformer#1]
When a less file is referenced in a tag, riot-jest-transformer attempts to resolve that path relative to the projects root instead of resolving relative to the file that referenced the path.

**Comment by tompascall** [comment]
Hi! I cannot reproduce the issue, in my tags the less files are resolved relative to the tag. Are your less files resolved well in simple javascript modules?

**Comment by bcartmell** [comment]
I haven't tried resolving my less files in JS modules yet.  I'll try it and update with my findings.
