### ISSUE TITLE
Babel 7

### ISSUE THREAD

**Issue by sambrenner** [tompascall/riot-jest-transformer#3]
I had some issues transforming tags in a project that uses Babel 7. [babel-preset-es2015-riot](https://github.com/riot/babel-preset-es2015-riot) is no longer needed, and [transform-es2015-modules-commonjs](https://babeljs.io/docs/en/babel-plugin-transform-es2015-modules-commonjs) handles es6 import syntax. 

What I think was happening was that my use of a Babel 7-configured .babelrc in my site code did not play well with the Babel 6 that was ultimately used by this library. The main issue I encountered was that `this` in a tag's `<script>` would come back as `undefined`, for example with 

```
this.on("mount", () => {
});

// throws error "Cannot read property on of undefined"
```

By upgrading riot-jest-transformer to use Babel 7, I'm now able to implement it in a project that also uses Babel 7.

I'll have a PR coming shortly that upgrades this library to use Babel 7, though I think it needs some extra eyes since I'm not too familiar with the inner workings of Jest transformers.

**Comment by tompascall** [comment]
Hi! thanks for your contribution. I've just published the new version of
the package.

Cheers,
tp
