### ISSUE TITLE
How to register preProcessors and postProcessors?

### ISSUE THREAD

**Issue by Acesmndr** [tompascall/riot-jest-transformer#8]
Since I use scss my tests are failing.
Adding support for these? https://riot.js.org/compiler/#pre-processors

![image](https://user-images.githubusercontent.com/4254571/64922935-6485e780-d7f4-11e9-85df-14346c74dcea.png)

**Comment by tompascall** [comment]
Hi! Have you registered your scss preprocessor in jest config at transform section?

**Comment by Acesmndr** [comment]
@tompascall I tried it but still it's not working. Here's my `jest.config.js`:

```js
{
    "moduleNameMapper": {
        "\\.(css|scss)$": "identity-obj-proxy"
    },
    "transform": {
        "^.+\\.jsx?$": "babel-jest",
        "^.+\\.riot$": "riot-jest-transformer",
        ".+\\.scss$": "jest-css-modules-transform"
    },
    "coverageDirectory": "../coverage"
}
```

**Comment by tompascall** [comment]
What version of riot-jest-transformer do you use? There is a new version for riot v4

**Comment by tompascall** [comment]
I tried to register jest-css-modules-transform in the demo project of this repo, and imported an scss file. The tests can run without failing.

**Comment by Acesmndr** [comment]
@tompascall I'm using the latest version of `riot-jest-transformer`. Actually I'm migrating from v3 of riot to v4.
It's an opensource project so I've created a PR for the test specs here:
https://github.com/Acesmndr/chrome-extension-boilerplate-riot/pull/8/files
or for the source code for my riot components: https://github.com/Acesmndr/chrome-extension-boilerplate-riot/tree/technical/riot-v4-tests/src/popup/components

**Comment by tompascall** [comment]
I'm on the update, I'd like to publish the next version of transformer till tomorrow.

**Comment by Acesmndr** [comment]
Sure! 🙇🚀

**Comment by Acesmndr** [comment]
Resolved with the new version of `riot-jest-transformer`. Working and tested in  https://github.com/Acesmndr/chrome-extension-boilerplate-riot/pull/9 . 🙇 🎉 🎉
