### ISSUE TITLE
SCSS registration failing for multiple riot components

### ISSUE THREAD

**Issue by Acesmndr** [tompascall/riot-jest-transformer#9]
It's working fine in my local machine but Travis CI test fails (showing the link to the riot-jest-transformer) now that I added multiple riot components. :(
I've tried updating yarn and matching the versions of node and everything but it's failing in the remote server.
Any idea on how to resolve this? https://github.com/Acesmndr/chrome-extension-boilerplate-riot/pull/8

![image](https://user-images.githubusercontent.com/4254571/65817584-d7e21d00-e228-11e9-9e09-dea2ab818147.png)

**Comment by tompascall** [comment]
I'll check it out

**Comment by tompascall** [comment]
I hope it will solve the problem. https://github.com/Acesmndr/chrome-extension-boilerplate-riot/pull/10

**Comment by Acesmndr** [comment]
Resolved with riot-jest-transformer v5.0.0 Thanks :bow:
